# Generated by Django 3.2.6 on 2021-09-30 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imgapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
